import type { AIProvider, AIAnalyzeResult, AIFixResult } from './aiProvider.js';
import { repoDb } from '../db/database.js';
import * as diffPkg from 'diff';

export class OpenAIProvider implements AIProvider {
  name = 'OpenAI / Compatible';

  private getApiKey(): string | undefined {
    return repoDb.getSetting('openai_api_key') || process.env.OPENAI_API_KEY || undefined;
  }

  private getBaseUrl(): string {
    return repoDb.getSetting('openai_base_url') || process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1';
  }

  private getModel(): string {
    return repoDb.getSetting('openai_model') || process.env.OPENAI_MODEL || 'gpt-4o-mini';
  }

  isAvailable(): boolean {
    return Boolean(this.getApiKey());
  }

  async analyzeRepository(context: {
    repoName: string;
    language: string;
    filesSummary: string;
    staticFindings: any[];
  }): Promise<AIAnalyzeResult> {
    const apiKey = this.getApiKey();
    if (!apiKey) throw new Error('OpenAI API key is not configured.');

    const prompt = `You are a Principal Code Reviewer and Security Architect.
Analyze the following repository context and static analysis findings.

Repository: ${context.repoName}
Primary Language: ${context.language}

=== Static Findings ===
${JSON.stringify(context.staticFindings, null, 2)}

=== Source Files ===
${context.filesSummary}

Respond in JSON matching schema:
{
  "summary": "High-level summary of code quality, architecture, security, and maintainability",
  "issues": [
    {
      "category": "security" | "quality" | "testing" | "architecture" | "documentation" | "dependencies",
      "severity": "critical" | "high" | "medium" | "low" | "info",
      "title": "Clear concise issue title",
      "description": "Detailed explanation of problem and impact",
      "file_path": "path/to/file",
      "line_number": 1,
      "code_snippet": "code snippet",
      "recommendation": "Actionable solution"
    }
  ]
}`;

    const res = await fetch(`${this.getBaseUrl()}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: this.getModel(),
        messages: [{ role: 'user', content: prompt }],
        response_format: { type: 'json_object' },
        temperature: 0.2,
      }),
    });

    if (!res.ok) {
      throw new Error(`OpenAI API error: ${res.status} ${res.statusText}`);
    }

    const data = (await res.json()) as any;
    const content = data.choices[0]?.message?.content || '{}';
    const parsed = JSON.parse(content);

    return {
      summary: parsed.summary || 'OpenAI Analysis completed.',
      issues: Array.isArray(parsed.issues) ? parsed.issues : [],
    };
  }

  async generateFix(params: {
    issue: any;
    fileContent: string;
    language: string;
  }): Promise<AIFixResult> {
    const apiKey = this.getApiKey();
    if (!apiKey) throw new Error('OpenAI API key is not configured.');

    const prompt = `Fix the following code issue:
Issue: ${params.issue.title}
Description: ${params.issue.description}
File: ${params.issue.file_path}
Recommendation: ${params.issue.recommendation}

Content:
${params.fileContent}

Respond in JSON format:
{
  "originalCode": "exact substring to replace",
  "suggestedCode": "replacement code",
  "explanation": "explanation of fix"
}`;

    const res = await fetch(`${this.getBaseUrl()}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: this.getModel(),
        messages: [{ role: 'user', content: prompt }],
        response_format: { type: 'json_object' },
        temperature: 0.1,
      }),
    });

    if (!res.ok) {
      throw new Error(`OpenAI API error: ${res.status}`);
    }

    const data = (await res.json()) as any;
    const parsed = JSON.parse(data.choices[0]?.message?.content || '{}');
    const originalCode = parsed.originalCode || '';
    const suggestedCode = parsed.suggestedCode || '';

    const patch = diffPkg.createPatch(
      params.issue.file_path,
      params.fileContent,
      params.fileContent.includes(originalCode)
        ? params.fileContent.replace(originalCode, suggestedCode)
        : params.fileContent,
      'original',
      'suggested'
    );

    return {
      originalCode,
      suggestedCode,
      diff: patch,
      explanation: parsed.explanation || 'Fix generated by OpenAI.',
    };
  }
}

export const openAIProvider = new OpenAIProvider();
